name: storybook-deploy
on:
    push:

permissions: # so we can upload the storybook
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - run: npm ci
            - run: npm run storybook:build
            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: 'storybook-static'
                target-folder: ${{ github.head_ref || github.ref_name }} 
    